### ISSUE TITLE
SyntaxError: Missing parentheses in call to 'print' [Python 3.5.1 on win32]

### ISSUE THREAD

**Issue by sginsbourg** [munrocape/harry#6]
Hi,

Does the following SyntaxError has any workaround ? Is it relevant to a specific Python version ?
[Python 3.5.1 (v3.5.1:37a07cee5969, Dec  6 2015, 01:54:25) [MSC v.1900 64 bit (AMD64)] on win32]

thanks,
Shay

Error details:

C:\HAR>harry -i C:\HAR\work\Test.har -o C:\HAR\work\T.jmx
Traceback (most recent call last):
  File "c:\users\sgins.shay-pc\appdata\local\programs\python\python35\lib\runpy.py", line 170, in _run_module_as_main
    "__main__", mod_spec)
  File "c:\users\sgins.shay-pc\appdata\local\programs\python\python35\lib\runpy.py", line 85, in _run_code
    exec(code, run_globals)
  File "C:\Users\sgins.SHAY-PC\AppData\Local\Programs\Python\Python35\Scripts\harry.exe__main__.py", line 5, in <module>
  File "c:\users\sgins.shay-pc\appdata\local\programs\python\python35\lib\site-packages\harry\harry.py", line 43
    print message
                ^
SyntaxError: Missing parentheses in call to 'print'

**Comment by DevonStrawn** [comment]
Having the same issue. Looks like Harry doesn't yet support Python3.

Installed on Python 2.7 successfully.
